"""
HTML Report Generator

Generates a modern HTML fairness audit report.

Author: FairLens
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Dict


class HTMLReportGenerator:
    """
    Generate HTML fairness audit reports.
    """

    def generate(
        self,
        dataset_info: Dict,
        fairlearn_metrics: Dict,
        aif360_metrics: Dict,
        mai: Dict,
        annex3: Dict,
    ) -> str:

        timestamp = datetime.now().strftime(
            "%Y-%m-%d %H:%M:%S"
        )

        html = f"""
<!DOCTYPE html>
<html>

<head>

<meta charset="UTF-8">

<title>FairLens Report</title>

<style>

body {{

font-family: Arial, Helvetica, sans-serif;
background:#f4f6f8;
padding:40px;
}}

.container {{

max-width:1200px;
margin:auto;
background:white;
padding:30px;
border-radius:10px;
box-shadow:0 5px 15px rgba(0,0,0,0.15);

}}

h1,h2{{
color:#1f3c88;
}}

table{{
width:100%;
border-collapse:collapse;
margin-bottom:30px;
}}

th{{
background:#1f3c88;
color:white;
padding:10px;
}}

td{{
border:1px solid #ddd;
padding:10px;
text-align:center;
}}

.pass{{
color:green;
font-weight:bold;
}}

.fail{{
color:red;
font-weight:bold;
}}

.card{{
background:#eef3fb;
padding:20px;
margin-bottom:25px;
border-radius:8px;
}}

</style>

</head>

<body>

<div class="container">

<h1>FairLens Fairness Audit Report</h1>

<p><b>Generated:</b> {timestamp}</p>

<hr>

<h2>Dataset Information</h2>

<div class="card">

<ul>

"""

        for key, value in dataset_info.items():

            html += f"<li><b>{key}</b>: {value}</li>"

        html += """
</ul>

</div>

"""

        # ---------------------------------------------------------
        # Fairlearn Table
        # ---------------------------------------------------------

        html += """
<h2>Fairlearn Metrics</h2>

<table>

<tr>

<th>Metric</th>
<th>Value</th>
<th>Threshold</th>
<th>Status</th>

</tr>

"""

        for metric in fairlearn_metrics.values():

            status = (
                "<span class='pass'>PASS</span>"
                if metric["passed"]
                else "<span class='fail'>FAIL</span>"
            )

            html += f"""

<tr>

<td>{metric['name']}</td>

<td>{metric['value']:.4f}</td>

<td>{metric['threshold']}</td>

<td>{status}</td>

</tr>

"""

        html += "</table>"

        # ---------------------------------------------------------
        # AIF360
        # ---------------------------------------------------------

        html += """
<h2>AIF360 Metrics</h2>

<table>

<tr>

<th>Metric</th>
<th>Value</th>
<th>Threshold</th>
<th>Status</th>

</tr>

"""

        for metric in aif360_metrics.values():

            status = (
                "<span class='pass'>PASS</span>"
                if metric["passed"]
                else "<span class='fail'>FAIL</span>"
            )

            html += f"""

<tr>

<td>{metric['name']}</td>

<td>{metric['value']:.4f}</td>

<td>{metric['threshold']}</td>

<td>{status}</td>

</tr>

"""

        html += "</table>"

        # ---------------------------------------------------------
        # MAI
        # ---------------------------------------------------------

        html += f"""

<h2>Metric Agreement Index</h2>

<div class="card">

<h3>

Overall Agreement

</h3>

<h1>

{mai['overall_agreement']:.4f}

</h1>

<table>

<tr>

<th>Metric</th>

<th>Agreement</th>

</tr>

"""

        for metric, score in mai[
            "metric_agreements"
        ].items():

            html += f"""

<tr>

<td>{metric}</td>

<td>{score:.4f}</td>

</tr>

"""

        html += """

</table>

</div>

"""

        # ---------------------------------------------------------
        # Annex III
        # ---------------------------------------------------------

        html += f"""

<h2>EU AI Act Annex III</h2>

<div class="card">

<p>

<b>High Risk:</b>

{annex3['high_risk']}

</p>

"""

        if annex3["categories"]:

            html += "<ul>"

            for category in annex3["categories"]:

                html += f"""

<li>

<b>{category['name']}</b>

<br>

{category['description']}

</li>

"""

            html += "</ul>"

        html += f"""

<p>

<b>Recommendation</b>

<br>

{annex3['recommendation']}

</p>

</div>

"""

        # ---------------------------------------------------------
        # Footer
        # ---------------------------------------------------------

        html += """

<hr>

<p>

Generated by

<b>FairLens</b>

</p>

</div>

</body>

</html>

"""

        return html

    def save(
        self,
        path: str,
        report: str,
    ):

        Path(path).write_text(
            report,
            encoding="utf-8",
        )